Repository MTES-MCT/histologe, pull requests merged in 2023-03, with the labels that each got.

#975 [BO - Signalement] Affichage des informations de non décence sur la fiche signalement
  migrations/Version20230224152702.php
  src/Controller/Back/BackSignalementController.php
  src/Controller/Back/BackSignalementQualificationController.php
  src/DataFixtures/Loader/LoadSignalementData.php
  src/Entity/Criticite.php
  src/Entity/Enum/QualificationStatus.php
  src/Entity/SignalementQualification.php
  src/Security/Voter/SignalementVoter.php
  src/Service/Signalement/SignalementQualificationService.php
  templates/_partials/_modal_edit_nde.html.twig
  templates/back/signalement/view.html.twig
  tests/Functional/Controller/BackPartnerControllerTest.php
  tests/Functional/Controller/BackSignalementControllerTest.php
  tests/Functional/Controller/BackSignalementQualificationControllerTest.php
  tests/Functional/Manager/SignalementManagerTest.php
  tests/Functional/Repository/PartnerRepositoryTest.php
  tests/Functional/Service/Signalement/SignalementQualificationServiceTest.php
  tests/Unit/Factory/CommuneFactoryTest.php
Labels: Non décence énergétique

#990 [BO - Dashboard] Correction de l'affichage des affectations des partenaires dans le tableau de bord
  assets/vue/components/dashboard/TheHistoAppDashboard.vue
Labels: Dashboard

#967 [BO - Dashboard] Cartes inactives pour admin partenaire
  README.md
  assets/vue/components/dashboard/TheHistoDashboardTables.vue
  config/app/widgets.yaml
  src/DataFixtures/Files/User.yml
  src/Service/DashboardWidget/WidgetDataKpiBuilder.php
Labels: Dashboard

#983 [Performance] Revue de la checklist performance recommandation symfony
  .docker/php-fpm/Dockerfile
  composer.json
  config/services.yaml
  scripts/postdeploy.sh
Labels: Performance

#965 [BO - Dashboard] Compteurs ne se mettent pas à jour (Clôtures global & partenaires)
  src/Dto/CountSignalement.php
  src/Entity/Suivi.php
  src/EventListener/ActivityListener.php
  src/Repository/NotificationRepository.php
  src/Repository/SignalementRepository.php
  src/Service/DashboardWidget/WidgetDataKpiBuilder.php
  src/Service/DashboardWidget/WidgetDataManagerCache.php
  templates/back/index.html.twig
  tests/Functional/EventSubscriber/SignalementClosedSubscriberTest.php
  tests/Functional/EventSubscriber/SignalementViewedSubscriberTest.php
  tests/Unit/Dto/CountSignalementTest.php
Labels: Dashboard

#998 Correction pour l'affichage du nombre de filtres actifs quand on clique depuis le Dashboard
  src/Controller/Back/BackCartographieController.php
  src/Controller/Back/BackController.php
  src/Service/SearchFilterService.php
Labels: Dashboard

#1013 [BO - Signalement] Refacto - Affichage des informations de non décence sur la fiche signalement
  assets/app.ts
  assets/controllers/form_nde.js
  src/Controller/Back/BackSignalementController.php
  src/Controller/Back/BackSignalementQualificationController.php
  src/Dto/Request/Signalement/QualificationNDERequest.php
  src/Entity/Signalement.php
  src/Manager/SignalementManager.php
  src/Service/Signalement/QualificationStatusService.php
  src/Service/Signalement/SignalementQualificationService.php
  src/Twig/AppExtension.php
  templates/_partials/_modal_edit_nde.html.twig
  templates/back/signalement/view.html.twig
  tests/Functional/Controller/BackSignalementQualificationControllerTest.php
  tests/Functional/Manager/SignalementManagerTest.php
  tests/Functional/Service/Signalement/QualificationStatusServiceTest.php
Labels: Non décence énergétique

#1008 [Performance] Audit de la table de signalement
  migrations/Version20230309141214.php
  src/Entity/Signalement.php
  src/Factory/SignalementFactory.php
  src/Manager/SignalementManager.php
  src/Service/Import/Signalement/SignalementImportMapper.php
  tests/Functional/Manager/SignalementManagerTest.php
  tests/Functional/Service/Import/Signalement/SignalementImportLoaderTest.php
  tests/Unit/Factory/SignalementFactoryTest.php
Labels: Performance

#1014 Stockage des fichiers directement sur le cloud lors de la saisie d'un signalement
  config/services.yaml
  src/Service/UploadHandlerService.php
  tests/Functional/Service/UploadHandlerServiceTest.php
Labels: Performance

#1004 Ajout de filtres NDE dans la liste des signalements
  src/Controller/Back/BackCartographieController.php
  src/Controller/Back/BackController.php
  src/DataFixtures/Loader/LoadSignalementData.php
  src/Entity/Signalement.php
  src/Entity/SignalementQualification.php
  src/Repository/SignalementQualificationRepository.php
  src/Security/Voter/UserVoter.php
  src/Service/SearchFilterService.php
  src/Service/Signalement/QualificationStatusService.php
  src/Service/Statistics/MotifClotureStatisticProvider.php
  templates/_partials/_search_filter_form.html.twig
  templates/back/table_result.html.twig
  tests/Unit/Entity/SignalementQualificationTest.php
  tests/Unit/Entity/SignalementTest.php
Labels: Non décence énergétique

#1012 [Performance] Améliorer les temps de réponse de la liste de signalements
  .env
  .env.sample
  assets/styles/histologe.scss
  config/packages/doctrine.yaml
  config/packages/twig.yaml
  config/services.yaml
  migrations/Version20230311184843.php
  migrations/Version20230313140816.php
  src/Command/UpdateSignalementLastSuiviAtCommand.php
  src/Controller/Back/BackCartographieController.php
  src/Controller/Back/BackController.php
  src/Controller/Back/BackDashboardController.php
  src/DataFixtures/Files/Signalement.yml
  src/DataFixtures/Loader/LoadSignalementData.php
  src/Dto/SignalementAffectationListView.php
  src/Entity/Enum/AffectationStatus.php
  src/Entity/Enum/SignalementStatus.php
  src/Entity/Signalement.php
  src/EventSubscriber/SuiviCreatedSubscriber.php
  src/Factory/SignalementAffectationListViewFactory.php
  src/Manager/SignalementManager.php
  src/Repository/NotificationRepository.php
  src/Repository/PartnerRepository.php
  src/Repository/SignalementRepository.php
  src/Repository/TagRepository.php
  src/Service/NewsActivitiesSinceLastLoginService.php
  src/Service/Notification/NotificationCounter.php
  src/Service/SearchFilterService.php
  src/Service/Signalement/SearchFilterOptionDataProvider.php
  src/Service/Signalement/SuiviHelper.php
  src/Twig/AppExtension.php
  templates/_partials/_search_filter_form.html.twig
  templates/back/index.html.twig
  templates/back/nav_bo.html.twig
  templates/back/table_result.html.twig
  tests/Functional/Controller/BackControllerTest.php
  tests/Functional/Factory/SignalementAffectationListViewFactoryTest.php
  tests/Functional/Manager/SignalementManagerTest.php
  tests/Functional/Service/Signalement/SearchFilterOptionDataProviderTest.php
Labels: Performance

#1036 [QA] formulaire de contact, possible d'avoir plusieurs signalements pour un déclarant
  src/FormHandler/ContactFormHandler.php
  src/Repository/SignalementRepository.php
  tests/Functional/FormHandler/ContactFormHandlerTest.php
Labels: bug

#1020 [BO - Dashboard] Modification du dashboard pour ajouter les cartes liées à la NDE
  assets/vue/components/dashboard/TheHistoAppDashboard.vue
  assets/vue/components/dashboard/TheHistoDashboardCards.vue
  assets/vue/components/dashboard/store.ts
  config/app/widgets.yaml
  package-lock.json
  src/Controller/Back/WidgetSettingsController.php
  src/Dto/CountSignalement.php
  src/Repository/AffectationRepository.php
  src/Repository/SignalementRepository.php
  src/Service/DashboardWidget/WidgetDataKpiBuilder.php
  src/Service/DashboardWidget/WidgetSettings.php
  src/Service/SearchFilterService.php
  tests/Unit/Service/DashboardWidget/WidgetSettingsTest.php
Labels: Non décence énergétique

#1047 [Design] Mise à jour de l'interface de l'Accueil, de Qui sommes-nous, de Contact
  assets/styles/histologe.scss
  public/img/Logo_label_2021.png
  public/img/about/logo-exclusion-energetique-big.png
  public/img/about/logo-exclusion-energetique.png
  public/img/about/logo-prix-gazette-commues-big.png
  public/img/about/logo-prix-gazette-commues.png
  public/img/about/logo-prix-initiatives-locales-big.png
  public/img/about/logo-prix-initiatives-locales.png
  public/img/about/logo-territoire-innovant-big.png
  public/img/about/logo-territoire-innovant.png
  public/img/exclusion-energetique.png
  public/img/gazette.png
  public/img/home/step-1.svg
  public/img/home/step-2.svg
  public/img/home/step-3.svg
  public/img/home/step-4.svg
  public/img/illustration-undraw-home.svg
  public/img/illustration-undraw-target.svg
  public/img/itheasfp.png
  templates/front/about.html.twig
  templates/front/contact.html.twig
  templates/front/index.html.twig
Labels: OKR

#1042 [Notification] en cas d absence de suivi partagé sur 30 jours, envoyer mail de suivi automatique / demander feedback à l usager
  cron.json
  src/Command/AskFeedbackUsagerCommand.php
  src/DataFixtures/Files/Signalement.yml
  src/DataFixtures/Files/Suivi.yml
  src/DataFixtures/Loader/LoadSignalementData.php
  src/Entity/Suivi.php
  src/EventListener/ActivityListener.php
  src/Factory/SuiviFactory.php
  src/FormHandler/ContactFormHandler.php
  src/Repository/SignalementRepository.php
  src/Repository/SuiviRepository.php
  src/Service/NotificationService.php
  src/Service/Signalement/SuiviHelper.php
  templates/back/signalement/view.html.twig
  templates/back/table_result.html.twig
  templates/emails/demande_feedback_usager_email.html.twig
  templates/front/suivi_signalement.html.twig
  tests/Functional/Command/AskFeedbackUsagerCommandTest.php
Labels: OKR
